name: fixarenda
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.5.0+1
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  fl_chart: ^0.68.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path: ^1.9.0
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.12
  change_app_package_name: ^1.3.0
  custom_lint: ^0.6.4
  floor_generator: ^1.5.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit_generator: ^8.1.2
  riverpod_lint: ^2.3.12
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/font/NotoSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/font/NotoSans-VariableFont_wdth,wght.ttf
          style: italic

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
    - assets/font/
